window:
  dimensions:
    columns: 180
    lines: 33
  padding:
    x: 30
    y: 30
  dynamic_padding: false
  decorations: buttonless
background_opacity: 1
scrolling:
  history: 1000
  multiplier: 3
font:
  normal:
    family: Fira Code
    style: Regular
  size: 13.0
  offset:
    x: 0
    y: 20
  glyph_offset:
    x: 0
    y: 10
draw_bold_text_with_bright_colors: true
colors:
  primary:
    background: '#1D1F21'
    foreground: '#FAFAFC'
  cursor:
    text: '#ecf0f1'
    cursor: '#35393c'
  selection:
    text: '#FAFAFC'
    background: '#FF757F'
  normal:
    black: '#1D1F21'
    red: '#FF757F'
    green: '#B8E994'
    yellow: '#FAD390'
    blue: '#6A89CC'
    magenta: '#D6A2E8'
    cyan: '#82CCDD'
    white: '#C5C8C6'
  bright:
    black: '#1D1F21'
    red: '#FF757F'
    green: '#B8E994'
    yellow: '#FAD390'
    blue: '#6A89CC'
    magenta: '#D6A2E8'
    cyan: '#82CCDD'
    white: '#FAFAFC'
# colors:
#   primary:
#     background: '0x2E3440'
#     foreground: '0xD8DEE9'
#   cursor:
#     text: '0x2E3440'
#     cursor: '0xD8DEE9'
#   selection:
#     text: '0xE5E9F0'
#     background: '0xBF616A'
#   normal:
#     black: '0x3B4252'
#     red: '0xBF616A'
#     green: '0xA3BE8C'
#     yellow: '0xEBCB8B'
#     blue: '0x81A1C1'
#     magenta: '0xB48EAD'
#     cyan: '0x88C0D0'
#     white: '0xE5E9F0'
#   bright:
#     black: '0x4C566A'
#     red: '0xBF616A'
#     green: '0xA3BE8C'
#     yellow: '0xEBCB8B'
#     blue: '0x81A1C1'
#     magenta: '0xB48EAD'
#     cyan: '0x8FBCBB'
#     white: '0xECEFF4'
cursor:
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Underline
key_bindings:
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: 28,      mods: Alt, chars: "{" }
  - { key: 25,      mods: Alt, chars: "}" }
  - { key: 37,      mods: Alt, chars: "@" }
  - { key: 26,      mods: Alt|Shift, chars: "\\" }
  - { key: 26,      mods: Alt, chars: "|" }
  - { key: 45,      mods: Alt, chars: "~" }
  - { key: 23,      mods: Alt, chars: "[" }
  - { key: 22,      mods: Alt, chars: "]" }
